force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Whenever an error is thrown anywhere in the system, a record will be added with vital information to debug the error.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Affected_Area__c.field-meta.xml
<CustomField>
    <fullName>Affected_Area__c</fullName>
    <description>The area of code affected by the exception.</description>
    <label>Affected Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Affected_Fields__c.field-meta.xml
<CustomField>
    <fullName>Affected_Fields__c</fullName>
    <description>Fields affected in a SaveResult error.</description>
    <label>Affected Fields</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>The location within the code where the error occured.</description>
    <label>Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The error message thrown with the exception.</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Record_IDs__c.field-meta.xml
<CustomField>
    <fullName>Record_IDs__c</fullName>
    <description>ID list of all records affected by that particular error.</description>
    <label>Record IDs</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <description>Status Code(s) associated with a SaveResult error.</description>
    <label>Status Code</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of exception thrown, whether standard or custom.</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorLogging.cls
/*
Developer: Evan Matthews <evan.matthews@callawaycloudconsulting.com>
Description:
    A ulitity class developed to create error logs from various exceptions that occur
    throughout the Apex landscape of any Org.  Can be dropped into an org along with the proper
    meta and custom object Error_Log__c files.  Utilizes ErrorHelper class to perform some tasks
    for error handling.
*/
public with sharing class ErrorLogging {

    // process a default exception and add it to the custom Error Log object
    public static Error_Log__c basicError(Exception e, String affectedArea) {
        Error_Log__c newLog = new Error_Log__c();
        newLog.Type__c = e.getTypeName();
        newLog.Message__c = e.getMessage();
        newLog.Stack_Trace__c = e.getStackTraceString();
        newLog.Location__c = e.getStackTraceString().split(':')[0];
        newLog.Affected_Area__c = affectedArea;
        insert newLog;
        return newLog;
    }

    // process a Database SaveResult error array and log to the custom Error Log object. Sorted by index
    public static Error_Log__c resultsByID(Database.SaveResult[] srList) {

        Error_Log__c log = new Error_Log__c();
        String[] msgList = new String[]{};
        String[] fieldsList = new String[]{};
        String[] statusList = new String[]{};

        for (Integer i=0;i<srList.size();i++) {
            if (!srList[i].isSuccess()) {
                for (Database.Error err : srList[i].getErrors()) {
                    msgList.add('index ['+i+']: ' + err.getMessage()+'; '+ '\n');
                    statusList.add('index ['+i+']: ' + err.getStatusCode()+'; '+ '\n');
                    fieldsList.add('index ['+i+']: ' + err.getFields()+'; '+ '\n');
                }
            }
        }

        log.Message__c = String.join(msgList,'');
        log.Status_Code__c = String.join(statusList,'');
        log.Affected_Fields__c = String.join(fieldsList,'');
        log.Type__c = 'Batch Insert/Update Errors';

        insert log;
        return log;
    }

    // process a Database UpsertResult error array and log to the custom Error Log object.  Sorted by ID
    public static Error_Log__c resultsByID(Database.UpsertResult[] urList, List<SObject> sObjects) {
        Error_Log__c log = new Error_Log__c();
        String[] msgList = new String[]{};
        String[] fieldsList = new String[]{};
        String[] statusList = new String[]{};

        for (Integer i=0;i<urList.size();i++) {
            if (!urList[i].isSuccess()) {
                for (Database.Error err : urList[i].getErrors()) {
                    msgList.add('(' + sObjects[i].Id + '): ' + err.getMessage()+'; '+ '\n');
                    statusList.add('(' + sObjects[i].Id + '): ' + err.getStatusCode()+'; '+ '\n');
                    fieldsList.add('(' + sObjects[i].Id + '): ' + err.getFields()+'; '+ '\n');
                }
            }
        }

        log.Message__c = String.join(msgList,'');
        log.Status_Code__c = String.join(statusList,'');
        log.Affected_Fields__c = String.join(fieldsList,'');
        log.Type__c = 'Batch Upsert Errors';

        insert log;
        return log;
    }

    // process a Database DeleteResult error array and log to the custom Error Log object.  Sorted by ID
    public static Error_Log__c resultsByID(Database.DeleteResult[] drList, List<SObject> sObjects) {
        Error_Log__c log = new Error_Log__c();
        String[] msgList = new String[]{};
        String[] fieldsList = new String[]{};
        String[] statusList = new String[]{};

        for (Integer i=0;i<drList.size();i++) {
            if (!drList[i].isSuccess()) {
                for (Database.Error err : drList[i].getErrors()) {
                    msgList.add('(' + sObjects[i].Id + '): ' + err.getMessage()+'; '+ '\n');
                    statusList.add('(' + sObjects[i].Id + '): ' + err.getStatusCode()+'; '+ '\n');
                    fieldsList.add('(' + sObjects[i].Id + '): ' + err.getFields()+'; '+ '\n');
                }
            }
        }

        log.Message__c = String.join(msgList,'');
        log.Status_Code__c = String.join(statusList,'');
        log.Affected_Fields__c = String.join(fieldsList,'');
        log.Type__c = 'Batch Delete Errors';

        insert log;
        return log;
    }

    // process results returned by ErrorHelper class on Save & Update.  Sorted by error
    public static Error_Log__c[] resultsByError(Database.SaveResult[] srList, List<SObject> sObjects) {
        Map<String, List<String>> errorMap = ErrorHelper.getErrorMap(srList, sObjects);
        List<Error_Log__c> newLogs = new List<Error_Log__c>();
        for (String err : errorMap.keySet()) {
            Error_Log__c log = new Error_Log__c();
            log.Message__c = err.split(';')[1].split('=')[1];
            log.Status_Code__c = err.split(';')[2].split('=')[1];
            log.Affected_Fields__c = err.split(';')[0].split('=')[1];
            if (errorMap.get(err) != null) {
                log.Record_IDs__c = String.join(errorMap.get(err),';\n');
            }
            log.Type__c = 'Batch Insert/Update Error';
            newLogs.add(log);
        }
        insert newLogs;
        return newLogs;
    }

    // include "upsertKey" for upsert results - this will be a custom ID field to set the id on results as failed upserts have Id=null
    public static Error_Log__c[] resultsByError(Database.UpsertResult[] urList, List<SObject> sObjects, String upsertKey) {
        Map<String, List<String>> errorMap = ErrorHelper.appendErrorMap(urList, sObjects, upsertKey, new Map<String, List<String>>());
        List<Error_Log__c> newLogs = new List<Error_Log__c>();
        for (String err : errorMap.keySet()) {
            Error_Log__c log = new Error_Log__c();
            log.Message__c = err.split(';')[1].split('=')[1];
            log.Status_Code__c = err.split(';')[2].split('=')[1];
            log.Affected_Fields__c = err.split(';')[0].split('=')[1];
            log.Record_IDs__c = String.join(errorMap.get(err),';\n');
            log.Type__c = 'Batch Upsert Error';
            newLogs.add(log);
        }
        insert newLogs;
        return newLogs;
    }

    // process results returned by ErrorHelper class on Delete.  Sorted by error
    public static Error_Log__c[] resultsByError(Database.DeleteResult[] drList, List<SObject> sObjects) {
        Map<String, List<String>> errorMap = ErrorHelper.appendErrorMap(drList, sObjects, new Map<String, List<String>>());
        List<Error_Log__c> newLogs = new List<Error_Log__c>();
        for (String err : errorMap.keySet()) {
            Error_Log__c log = new Error_Log__c();
            log.Message__c = err.split(';')[1].split('=')[1];
            log.Status_Code__c = err.split(';')[2].split('=')[1];
            log.Affected_Fields__c = err.split(';')[0].split('=')[1];
            log.Record_IDs__c = String.join(errorMap.get(err),';\n');
            log.Type__c = 'Batch Delete Error';
            newLogs.add(log);
        }
        insert newLogs;
        return newLogs;
    }
}

/*
    Want to grab all errors from a Database.SaveResult/UpdateResult/DeleteResult array and concat
    so that they can live in one place and not write a new log for each error.  Check ErrorHelper.cls
    for ideas.
*/