force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Whenever an error is thrown anywhere in the system, a record will be added with vital information to debug the error.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The error message thrown with the exception.</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DeleteErrorLogBatch_Test.cls
@isTest
private class DeleteErrorLogBatch_Test {

    @testSetup
    static void setup() {
        List<Error_Log__c> logs = new List<Error_Log__c>();

        // insert 10 Error Logs
        for (Integer i=0;i<10;i++) {
            logs.add(new Error_Log__c(Message__c='Log '+i));
        }

        insert logs;
    }

    @isTest static void batchDeleteTest() {

        String cron = '0 0 14 * * ?';

        Test.startTest();
        DeleteErrorLogBatch logBatch = new DeleteErrorLogBatch();
        Id batchId = Database.executeBatch(logBatch);
        String jobID = System.schedule('ScheduledApexTest', cron, new DeleteErrorLogBatch());
        Test.stopTest();

        // after the testing stops, assert records were updated properly
        System.assertEquals(0, [SELECT count() FROM Error_Log__c]);
    }
}